//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the igvc_image package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __igvc_image__LINEFILTERCONFIG_H__
#define __igvc_image__LINEFILTERCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace igvc_image
{
  class LineFilterConfigStatics;
  
  class LineFilterConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(LineFilterConfig &config, const LineFilterConfig &max, const LineFilterConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const LineFilterConfig &config1, const LineFilterConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, LineFilterConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const LineFilterConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LineFilterConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const LineFilterConfig &config) const = 0;
      virtual void getValue(const LineFilterConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T LineFilterConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (LineFilterConfig::* field);

      virtual void clamp(LineFilterConfig &config, const LineFilterConfig &max, const LineFilterConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const LineFilterConfig &config1, const LineFilterConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, LineFilterConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const LineFilterConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, LineFilterConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const LineFilterConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const LineFilterConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, LineFilterConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, LineFilterConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<LineFilterConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(LineFilterConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("hue_lower"==(*_i)->name){hue_lower = boost::any_cast<int>(val);}
        if("hue_upper"==(*_i)->name){hue_upper = boost::any_cast<int>(val);}
        if("saturation_lower"==(*_i)->name){saturation_lower = boost::any_cast<int>(val);}
        if("saturation_upper"==(*_i)->name){saturation_upper = boost::any_cast<int>(val);}
        if("value_lower"==(*_i)->name){value_lower = boost::any_cast<int>(val);}
        if("value_upper"==(*_i)->name){value_upper = boost::any_cast<int>(val);}
        if("threshold_image_debug"==(*_i)->name){threshold_image_debug = boost::any_cast<bool>(val);}
        if("blur_kernel_size"==(*_i)->name){blur_kernel_size = boost::any_cast<int>(val);}
        if("erosion_bool"==(*_i)->name){erosion_bool = boost::any_cast<bool>(val);}
        if("erosion_element"==(*_i)->name){erosion_element = boost::any_cast<int>(val);}
        if("erosion_size"==(*_i)->name){erosion_size = boost::any_cast<int>(val);}
        if("dilation_bool"==(*_i)->name){dilation_bool = boost::any_cast<bool>(val);}
        if("dilation_element"==(*_i)->name){dilation_element = boost::any_cast<int>(val);}
        if("dilation_size"==(*_i)->name){dilation_size = boost::any_cast<int>(val);}
        if("morphology_bool"==(*_i)->name){morphology_bool = boost::any_cast<bool>(val);}
        if("morphology_operation"==(*_i)->name){morphology_operation = boost::any_cast<int>(val);}
        if("morphology_element"==(*_i)->name){morphology_element = boost::any_cast<int>(val);}
        if("morphology_size"==(*_i)->name){morphology_size = boost::any_cast<int>(val);}
        if("canny_thresh1"==(*_i)->name){canny_thresh1 = boost::any_cast<double>(val);}
        if("canny_thresh2"==(*_i)->name){canny_thresh2 = boost::any_cast<double>(val);}
        if("canny_apeture_size"==(*_i)->name){canny_apeture_size = boost::any_cast<int>(val);}
        if("hough_rho"==(*_i)->name){hough_rho = boost::any_cast<double>(val);}
        if("hough_theta"==(*_i)->name){hough_theta = boost::any_cast<double>(val);}
        if("hough_threshold"==(*_i)->name){hough_threshold = boost::any_cast<int>(val);}
        if("hough_min_line_length"==(*_i)->name){hough_min_line_length = boost::any_cast<double>(val);}
        if("hough_min_line_gap"==(*_i)->name){hough_min_line_gap = boost::any_cast<double>(val);}
      }
    }

    int hue_lower;
int hue_upper;
int saturation_lower;
int saturation_upper;
int value_lower;
int value_upper;
bool threshold_image_debug;
int blur_kernel_size;
bool erosion_bool;
int erosion_element;
int erosion_size;
bool dilation_bool;
int dilation_element;
int dilation_size;
bool morphology_bool;
int morphology_operation;
int morphology_element;
int morphology_size;
double canny_thresh1;
double canny_thresh2;
int canny_apeture_size;
double hough_rho;
double hough_theta;
int hough_threshold;
double hough_min_line_length;
double hough_min_line_gap;

    bool state;
    std::string name;

    
}groups;



//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int hue_lower;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int hue_upper;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int saturation_lower;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int saturation_upper;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int value_lower;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int value_upper;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool threshold_image_debug;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int blur_kernel_size;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool erosion_bool;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int erosion_element;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int erosion_size;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool dilation_bool;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int dilation_element;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int dilation_size;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      bool morphology_bool;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int morphology_operation;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int morphology_element;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int morphology_size;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double canny_thresh1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double canny_thresh2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int canny_apeture_size;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_rho;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_theta;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int hough_threshold;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_min_line_length;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      double hough_min_line_gap;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("LineFilterConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const LineFilterConfig &__max__ = __getMax__();
      const LineFilterConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const LineFilterConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const LineFilterConfig &__getDefault__();
    static const LineFilterConfig &__getMax__();
    static const LineFilterConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const LineFilterConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void LineFilterConfig::ParamDescription<std::string>::clamp(LineFilterConfig &config, const LineFilterConfig &max, const LineFilterConfig &min) const
  {
    return;
  }

  class LineFilterConfigStatics
  {
    friend class LineFilterConfig;
    
    LineFilterConfigStatics()
    {
LineFilterConfig::GroupDescription<LineFilterConfig::DEFAULT, LineFilterConfig> Default("Default", "", 0, 0, true, &LineFilterConfig::groups);
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hue_lower = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hue_lower = 180;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hue_lower = 85;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("hue_lower", "int", 0, "Threshold - hue lower", "", &LineFilterConfig::hue_lower)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("hue_lower", "int", 0, "Threshold - hue lower", "", &LineFilterConfig::hue_lower)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hue_upper = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hue_upper = 180;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hue_upper = 120;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("hue_upper", "int", 0, "Threshold - hue upper", "", &LineFilterConfig::hue_upper)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("hue_upper", "int", 0, "Threshold - hue upper", "", &LineFilterConfig::hue_upper)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.saturation_lower = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.saturation_lower = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.saturation_lower = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("saturation_lower", "int", 0, "Threshold - saturation lower", "", &LineFilterConfig::saturation_lower)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("saturation_lower", "int", 0, "Threshold - saturation lower", "", &LineFilterConfig::saturation_lower)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.saturation_upper = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.saturation_upper = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.saturation_upper = 25;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("saturation_upper", "int", 0, "Threshold - saturation upper", "", &LineFilterConfig::saturation_upper)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("saturation_upper", "int", 0, "Threshold - saturation upper", "", &LineFilterConfig::saturation_upper)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.value_lower = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.value_lower = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.value_lower = 240;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("value_lower", "int", 0, "Threshold - value lower", "", &LineFilterConfig::value_lower)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("value_lower", "int", 0, "Threshold - value lower", "", &LineFilterConfig::value_lower)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.value_upper = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.value_upper = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.value_upper = 255;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("value_upper", "int", 0, "Threshold - value upper", "", &LineFilterConfig::value_upper)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("value_upper", "int", 0, "Threshold - value upper", "", &LineFilterConfig::value_upper)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.threshold_image_debug = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.threshold_image_debug = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.threshold_image_debug = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("threshold_image_debug", "bool", 0, "Threshold image diplay window enable", "", &LineFilterConfig::threshold_image_debug)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("threshold_image_debug", "bool", 0, "Threshold image diplay window enable", "", &LineFilterConfig::threshold_image_debug)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.blur_kernel_size = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.blur_kernel_size = 20;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.blur_kernel_size = 7;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("blur_kernel_size", "int", 0, "Kernel size for the bilateral filter", "", &LineFilterConfig::blur_kernel_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("blur_kernel_size", "int", 0, "Kernel size for the bilateral filter", "", &LineFilterConfig::blur_kernel_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.erosion_bool = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.erosion_bool = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.erosion_bool = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("erosion_bool", "bool", 0, "Erosion morphological filter enable", "", &LineFilterConfig::erosion_bool)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("erosion_bool", "bool", 0, "Erosion morphological filter enable", "", &LineFilterConfig::erosion_bool)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.erosion_element = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.erosion_element = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.erosion_element = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("erosion_element", "int", 0, "Erosion morphological filter kernel type", "", &LineFilterConfig::erosion_element)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("erosion_element", "int", 0, "Erosion morphological filter kernel type", "", &LineFilterConfig::erosion_element)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.erosion_size = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.erosion_size = 25;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.erosion_size = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("erosion_size", "int", 0, "Erosion filter size", "", &LineFilterConfig::erosion_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("erosion_size", "int", 0, "Erosion filter size", "", &LineFilterConfig::erosion_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.dilation_bool = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.dilation_bool = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.dilation_bool = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("dilation_bool", "bool", 0, "Dilation morphological filter enable", "", &LineFilterConfig::dilation_bool)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("dilation_bool", "bool", 0, "Dilation morphological filter enable", "", &LineFilterConfig::dilation_bool)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.dilation_element = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.dilation_element = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.dilation_element = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("dilation_element", "int", 0, "Dilation morphological filter kernel type", "", &LineFilterConfig::dilation_element)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("dilation_element", "int", 0, "Dilation morphological filter kernel type", "", &LineFilterConfig::dilation_element)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.dilation_size = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.dilation_size = 25;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.dilation_size = 7;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("dilation_size", "int", 0, "Dialtion filter size", "", &LineFilterConfig::dilation_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("dilation_size", "int", 0, "Dialtion filter size", "", &LineFilterConfig::dilation_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.morphology_bool = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.morphology_bool = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.morphology_bool = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("morphology_bool", "bool", 0, "Other morphological filter enable", "", &LineFilterConfig::morphology_bool)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<bool>("morphology_bool", "bool", 0, "Other morphological filter enable", "", &LineFilterConfig::morphology_bool)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.morphology_operation = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.morphology_operation = 4;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.morphology_operation = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("morphology_operation", "int", 0, "Other morphological filter operation type", "", &LineFilterConfig::morphology_operation)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("morphology_operation", "int", 0, "Other morphological filter operation type", "", &LineFilterConfig::morphology_operation)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.morphology_element = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.morphology_element = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.morphology_element = 2;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("morphology_element", "int", 0, "Other morphological filter kernel type", "", &LineFilterConfig::morphology_element)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("morphology_element", "int", 0, "Other morphological filter kernel type", "", &LineFilterConfig::morphology_element)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.morphology_size = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.morphology_size = 25;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.morphology_size = 6;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("morphology_size", "int", 0, "Other morphological filter size", "", &LineFilterConfig::morphology_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("morphology_size", "int", 0, "Other morphological filter size", "", &LineFilterConfig::morphology_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.canny_thresh1 = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.canny_thresh1 = 2480.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.canny_thresh1 = 50.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("canny_thresh1", "double", 0, "Other morphological filter operation type", "", &LineFilterConfig::canny_thresh1)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("canny_thresh1", "double", 0, "Other morphological filter operation type", "", &LineFilterConfig::canny_thresh1)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.canny_thresh2 = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.canny_thresh2 = 2480.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.canny_thresh2 = 250.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("canny_thresh2", "double", 0, "Other morphological filter kernel type", "", &LineFilterConfig::canny_thresh2)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("canny_thresh2", "double", 0, "Other morphological filter kernel type", "", &LineFilterConfig::canny_thresh2)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.canny_apeture_size = 1;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.canny_apeture_size = 7;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.canny_apeture_size = 3;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("canny_apeture_size", "int", 0, "Other morphological filter size", "", &LineFilterConfig::canny_apeture_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("canny_apeture_size", "int", 0, "Other morphological filter size", "", &LineFilterConfig::canny_apeture_size)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_rho = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_rho = 180.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_rho = 1.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_rho", "double", 0, "Hough Rho", "", &LineFilterConfig::hough_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_rho", "double", 0, "Hough Rho", "", &LineFilterConfig::hough_rho)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_theta = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_theta = 6.28318530718;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_theta = 0.0174532925199;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_theta", "double", 0, "Hough Theta", "", &LineFilterConfig::hough_theta)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_theta", "double", 0, "Hough Theta", "", &LineFilterConfig::hough_theta)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_threshold = 0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_threshold = 2480;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_threshold = 50;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("hough_threshold", "int", 0, "Hough Threshold", "", &LineFilterConfig::hough_threshold)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<int>("hough_threshold", "int", 0, "Hough Threshold", "", &LineFilterConfig::hough_threshold)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_min_line_length = 3.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_min_line_length = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_min_line_length = 20.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_min_line_length", "double", 0, "Hough min line length", "", &LineFilterConfig::hough_min_line_length)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_min_line_length", "double", 0, "Hough min line length", "", &LineFilterConfig::hough_min_line_length)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.hough_min_line_gap = 0.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.hough_min_line_gap = 100.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.hough_min_line_gap = 10.0;
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_min_line_gap", "double", 0, "Hough min line gap", "", &LineFilterConfig::hough_min_line_gap)));
//#line 259 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(LineFilterConfig::AbstractParamDescriptionConstPtr(new LineFilterConfig::ParamDescription<double>("hough_min_line_gap", "double", 0, "Hough min line gap", "", &LineFilterConfig::hough_min_line_gap)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(LineFilterConfig::AbstractGroupDescriptionConstPtr(new LineFilterConfig::GroupDescription<LineFilterConfig::DEFAULT, LineFilterConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<LineFilterConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<LineFilterConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<LineFilterConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    LineFilterConfig __max__;
    LineFilterConfig __min__;
    LineFilterConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const LineFilterConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static LineFilterConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &LineFilterConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const LineFilterConfig &LineFilterConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const LineFilterConfig &LineFilterConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const LineFilterConfig &LineFilterConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<LineFilterConfig::AbstractParamDescriptionConstPtr> &LineFilterConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<LineFilterConfig::AbstractGroupDescriptionConstPtr> &LineFilterConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const LineFilterConfigStatics *LineFilterConfig::__get_statics__()
  {
    const static LineFilterConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = LineFilterConfigStatics::get_instance();
    
    return statics;
  }

//#line 37 "/home/igvc/catkin_ws/src/igvc_image/line_filter/cfg/LineFilter.cfg"
      const int LineFilter_1 = 1;
//#line 37 "/home/igvc/catkin_ws/src/igvc_image/line_filter/cfg/LineFilter.cfg"
      const int LineFilter_3 = 3;
//#line 37 "/home/igvc/catkin_ws/src/igvc_image/line_filter/cfg/LineFilter.cfg"
      const int LineFilter_5 = 5;
//#line 37 "/home/igvc/catkin_ws/src/igvc_image/line_filter/cfg/LineFilter.cfg"
      const int LineFilter_7 = 7;
}

#endif // __LINEFILTERRECONFIGURATOR_H__
