set(_CATKIN_CURRENT_PACKAGE "triclops_vision")
set(triclops_vision_MAINTAINER "user1 <user1@todo.todo>")
set(triclops_vision_DEPRECATED "")
set(triclops_vision_VERSION "0.0.0")
set(triclops_vision_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "cv_bridge" "sensor_msgs" "opencv2")
set(triclops_vision_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "image_transport" "cv_bridge" "sensor_msgs" "opencv2")
set(triclops_vision_BUILDTOOL_DEPENDS "catkin")